name: Add Issue to Kanban

on:
  issues:
    types: [opened]

jobs:
  add_to_kanban:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Backlog
        uses: actions/add-to-project@v1.0.2
        with:
          project_name: "Quantum Tomography Development"
          column_name: "Backlog"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Priority Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: P1
